// Generates demo/standalone.html: the same playground, but with the library pasted in
// rather than imported. An inline module script runs fine from file://; only module
// *fetches* are blocked there, which is why demo/index.html needs a server and this
// does not. Run `npm run demo:build` after changing src/ or demo/index.html.
import { readFileSync, writeFileSync } from 'node:fs';

const read = (f) => readFileSync(new URL(f, import.meta.url), 'utf8');
// Strip the module syntax: the concatenated result is one scope, so the imports have
// nothing to resolve and the exports have nowhere to go.
const inline = (f) => read(f).replace(/^import [^\n]*\n/gm, '').replace(/^export /gm, '');

const IMPORT = "import { createInkfield } from '../src/inkfield.js';";

export function build() {
  const html = read('./index.html');
  if (!html.includes(IMPORT)) throw new Error(`demo/index.html no longer contains:\n${IMPORT}`);
  return html
    .replace('<title>inkfield — playground</title>',
             '<title>inkfield — standalone playground</title>')
    .replace(IMPORT, [
      '// --- generated by demo/build.mjs, do not edit: src/solver.js + src/inkfield.js ---',
      inline('../src/solver.js'),
      inline('../src/inkfield.js'),
      '// --- end generated ---',
    ].join('\n'));
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const out = new URL('./standalone.html', import.meta.url);
  writeFileSync(out, build());
  console.log(`wrote ${out.pathname} — open it directly, no server needed`);
}
