// Generates the repo-root index.html from demo/index.html, with the library pasted in
// rather than imported. That one file is what GitHub Pages serves and what opens by
// double-click: file:// blocks module *fetches*, not inline module scripts, which is why
// demo/index.html needs a server and the generated copy does not.
// Run `npm run demo:build` after changing src/ or demo/index.html.
import { readFileSync, writeFileSync } from 'node:fs';

const read = (f) => readFileSync(new URL(f, import.meta.url), 'utf8');
// Strip the module syntax: the concatenated result is one scope, so the imports have
// nothing to resolve and the exports have nowhere to go.
const inline = (f) => read(f).replace(/^import [^\n]*\n/gm, '').replace(/^export /gm, '');

const IMPORT = "import { createInkfield } from '../src/inkfield.js';";

export function build() {
  const html = read('./index.html');
  if (!html.includes(IMPORT)) throw new Error(`demo/index.html no longer contains:\n${IMPORT}`);
  return html
    .replace('<!DOCTYPE html>',
             '<!DOCTYPE html>\n<!-- Generated by demo/build.mjs from demo/index.html. Do not edit. -->')
    .replace(IMPORT, [
      '// --- generated by demo/build.mjs, do not edit: src/solver.js + src/inkfield.js ---',
      inline('../src/solver.js'),
      inline('../src/inkfield.js'),
      '// --- end generated ---',
    ].join('\n'));
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const out = new URL('../index.html', import.meta.url);
  writeFileSync(out, build());
  console.log(`wrote ${out.pathname} — open it directly, no server needed`);
}
